LARA authors can mark an activity to use the activity player
concord-consortium/lara pull request #652
Opened 2020-11-17 21:04 UTC by emcelroy

https://www.pivotaltracker.com/story/show/174824765

[#174824765]

* Add AP-only option to activity & sequence. 
* Limit embeddable types for AP-only activities/sequences
* Move AP url methods to models.

2020-11-18 21:36 UTC, emcelroy commented
@scytacki Do you think it's necessary to correct the issues identified by Code Climate?

2020-11-30 18:19 UTC, scytacki requested changes
I found a few things to change.

2020-12-01 22:52 UTC, emcelroy commented on app/views/lightweight_activities/new.html.haml
> +      (Official CC activities appear in the STEM Resource Finder.)
@scytacki Guess I assumed it corresponded with the similar option in portal settings, but it doesn't. Yeah, it doesn't seem to do much of anything in LARA either, though I'm not 100% sure. It's used to determine whether to add an "official" or "community" class to activity items listed on pages that list activities, but those classes don't seem to be used for anything.

I see some places where the option also seems to be used for activity filtering, but I'm not aware of any pages in LARA where filtering options like those are available.

I've removed the note I added, but left the option in for now.

2020-12-01 22:57 UTC, emcelroy commented on app/models/publishable.rb
> +      portal_publish_with_token(user.authentication_token(auth_portal.strategy_name),auth_portal,self_url,true,json)
@scytacki I'm afraid I've forgotten, too. Sorry. Does it maybe have to do with the fact that if the runtime is Activity Player, we use an API, but if the runtime is LARA, we don't?

![image](https://user-images.githubusercontent.com/367459/100806465-802bdc80-33fe-11eb-9512-3e4c6f00e2a7.png)

2020-12-04 14:37 UTC, scytacki requested changes
The changes look good to me.
However this broke some spec tests, so you need to fix those before we can merge.

2020-12-07 05:09 UTC, scytacki approved these changes
Looks good to me.

2020-12-07 05:12 UTC, merged