Added getFirebaseJwt to authoring mode in interactive api client [#178284894]
concord-consortium/lara pull request #724
Opened 2021-07-02 19:55 UTC by dougmartin

2021-07-06 13:29 UTC, scytacki requested changes
This looks good overall. 
The only problem I found was that it implies that modals are supported in authoring, but I don't think they are.
I'll try to track this down myself, since Doug is on vacation now.

2021-07-06 13:29 UTC, scytacki commented on lara-typescript/src/page-item-authoring/common/components/interactive-authoring.tsx
> +      },
I don't see new code supporting modals during authoring, was this supported before and just not added to the hostFeatures?

2021-07-12 19:37 UTC, scytacki commented on lara-typescript/src/page-item-authoring/common/components/interactive-authoring.tsx
> +      },
I removed this, because I didn't see any modal support during authoring.

2021-07-12 19:42 UTC, scytacki commented
Besides the changes to the tests, I bumped the version to `1.0.4` since @kswenson got in a PR before this one.

I also made 2 other changes:
- removed the check for the mode and now the client just looks at the hostFeatures to see if the host supports JWTs
- removed the code in this PR before which was saying the modal api was supported by the authoring interactive host

2021-07-12 20:15 UTC, kswenson reviewed
👍 Looks good

2021-07-12 20:15 UTC, kswenson commented on lara-typescript/src/interactive-api-client/api.ts
> +          && initMsg.hostFeatures?.getFirebaseJwt?.version === "1.0.0") {
Can be simplified to:
```suggestion
      if (initMsg?.hostFeatures?.getFirebaseJwt?.version === "1.0.0") {
```

2021-07-12 20:15 UTC, kswenson approved these changes
👍 Looks good

2021-07-16 17:20 UTC, merged