Duplicating Activity Player activities
concord-consortium/lara pull request #733
Opened 2021-08-09 22:32 UTC by emcelroy

PT Story: https://www.pivotaltracker.com/story/show/176057523

[#176057523]

2021-08-12 20:10 UTC, scytacki requested changes
Overall looks good. I found an issue with the tests though where they aren't correctly exercising all of the code.

2021-08-12 20:10 UTC, scytacki commented on spec/support/shared_examples/remote_duplicate_support.rb
> +        post :remote_duplicate, id: resource.id, user_email: user_email, add_to_portal: portal_url, author_url: author_url
This should only send the author_url when the home controller is being tested.
I'd suggest removing `let(:author_url)` from this file. 
And moving the `let(:aruthor_url)...` up into `it_behaves_like "remote duplicate support" do` block in the home_controller_spec.

I think if the author_url is undefined or nil then this line in make_request won't send the parameter. But you might need to change it so it author_url key isn't even in the hash send to the post method.

2021-08-13 03:42 UTC, emcelroy commented on app/controllers/remote_duplicate_support.rb
> +      resource = @activity || @sequence
Thanks. I believe this is fixed now.

2021-08-16 15:11 UTC, scytacki approved these changes
Looks good.

2021-08-16 15:11 UTC, merged